Repository devruso/soulpet-front, pull requests merged in 2023-05, with the labels that each got.

#33 Relatorio pdf clientes
  src/pages/Clientes/Clientes.jsx
Labels: enhancement

#35 pagina de servicos com listagem criada
  src/App.js
  src/components/Header/Header.jsx
  src/pages/Servicos/Servicos.jsx
Labels: enhancement

#37 correção CSS
  src/pages/AdicionarPet/Add-style.css
  src/pages/AdicionarPet/AdicionarPet.jsx
  src/pages/AdicionarServico/AddServico.css
  src/pages/AdicionarServico/AdicionarServico.jsx
Labels: duplicate

#38 Pagina de editar servicos
  src/App.js
  src/pages/EditarServico/EditaServico.jsx
  src/pages/Servicos/Servicos.jsx
Labels: enhancement

#39 remoção de servico na página de servicos
  src/pages/Servicos/Servicos.jsx
Labels: enhancement

#41 Página informações do cliente
  src/App.js
  src/pages/Clientes/Clientes.jsx
  src/pages/InformacoesCliente/InformacoesCliente.jsx
Labels: enhancement

#42 Paginação pet front
  src/components/Pagination/Pagination.jsx
  src/pages/Pets/Pets.jsx
Labels: enhancement

#46 adicao de link no header e ajustes no app.js
  src/App.js
  src/components/Header/Header.jsx
Labels: duplicate

#47 subindo adicao de pedidos
  src/App.js
  src/pages/NovoPedido/NovoPedido.jsx
Labels: enhancement

#48 atualizar pedido
  src/App.js
  src/pages/AtualizarPedido/AtualizarPedido.jsx
Labels: enhancement

#45 Readme e License front-end
  LICENSE.md
  README.md
Labels: enhancement

#50 Campo de seleção de estado e cidade
  src/pages/NovoCliente/NovoCliente.jsx
Labels: documentation, enhancement

#52 Listagem de Agendamentos
  src/App.js
  src/pages/Agendamentos/Agendamentos.jsx
Labels: enhancement

#54 Alteração nas rotas de serviço Front-end
  src/pages/AdicionarServico/AdicionarServico.jsx
  src/pages/EditarServico/EditaServico.jsx
  src/pages/Servicos/Servicos.jsx
Labels: duplicate

#53 Estilização parte 1
  package-lock.json
  package.json
  src/index.js
  src/index.scss
  src/pages/AdicionarPet/Add-style.css
  src/pages/AdicionarPet/AdicionarPet.jsx
  src/pages/AdicionarProduto/AdicionarProduto.jsx
  src/pages/Clientes/Clientes.jsx
  src/pages/NovoCliente/NovoCliente.jsx
  src/pages/NovoPedido/NovoPedido.jsx
  src/pages/Pedidos/Pedidos.jsx
  src/pages/Pets/Pets.jsx
  src/pages/Produtos/Produtos.jsx
Labels: enhancement

#57 correcao parcial em pedidos
  src/pages/Pedidos/Pedidos.jsx
Labels: duplicate

#60 botão de adicionar serviço em serviços
  src/pages/Servicos/Servicos.jsx
Labels: duplicate

#62 correcao rota de adicionar servico
  src/pages/Servicos/Servicos.jsx
Labels: duplicate

#63 adicionar agendamento
  src/App.js
  src/components/Header/Header.jsx
  src/pages/AdicionarAgendamento/AdicionarAgendamento.jsx
  src/pages/Agendamentos/Agendamentos.jsx
Labels: enhancement

#64 Estilização parte 2
  src/index.scss
  src/pages/EditaCliente/EditaCliente.jsx
  src/pages/EditaPet/AddPet-style.css
  src/pages/EditaPet/EditaPet.jsx
  src/pages/EditaProduto/EditaProduto.jsx
  src/pages/EditarServico/EditaServico.jsx
  src/pages/NovoCliente/NovoCliente.jsx
  src/pages/Pedidos/Pedidos.jsx
  src/pages/Produtos/Produtos.jsx
  src/pages/Servicos/Servicos.jsx
Labels: enhancement

#65 Correção serviços
  src/pages/Servicos/Servicos.jsx
Labels: duplicate

#66 Estilização parte 3
  src/pages/AdicionarAgendamento/AdicionarAgendamento.jsx
  src/pages/Agendamentos/Agendamentos.jsx
  src/pages/Pets/Pets.jsx
  src/pages/Servicos/Servicos.jsx
Labels: enhancement
